using System;
using System.Globalization;
using System.Text.RegularExpressions;

namespace App.Utilities
{
    public class AppUtilities
    {
        public static bool IsValidEmail(string email)
        {
            if (string.IsNullOrWhiteSpace(email))
                return false;

            try
            {
                // Normalize the domain
                email = Regex.Replace(
                    email,
                    @"(@)(.+)$",
                    DomainMapper,
                    RegexOptions.None,
                    TimeSpan.FromMilliseconds(200)
                );

                // Examines the domain part of the email and normalizes it.
                string DomainMapper(Match match)
                {
                    // Use IdnMapping class to convert Unicode domain names.
                    var idn = new IdnMapping();

                    // Pull out and process domain name (throws ArgumentException on invalid)
                    string domainName = idn.GetAscii(match.Groups[2].Value);

                    return match.Groups[1].Value + domainName;
                }
            }
            catch
            {
                return false;
            }

            try
            {
                return Regex.IsMatch(
                    email,
                    @"^[^@\s]+@[^@\s]+\.[^@\s]+$",
                    RegexOptions.IgnoreCase,
                    TimeSpan.FromMilliseconds(250)
                );
            }
            catch (RegexMatchTimeoutException)
            {
                return false;
            }
        }

        public static string GenerateSlug(string str, bool hierarchical = true)
        {
            var slug = str.Trim().ToLowerInvariant();

            string[] decomposed = new string[]
            {
                "à",
                "á",
                "ạ",
                "ả",
                "ã",
                "â",
                "ầ",
                "ấ",
                "ậ",
                "ẩ",
                "ẫ",
                "ă",
                "ằ",
                "ắ",
                "ặ",
                "ẳ",
                "ẵ",
                "è",
                "é",
                "ẹ",
                "ẻ",
                "ẽ",
                "ê",
                "ề",
                "ế",
                "ệ",
                "ể",
                "ễ",
                "ì",
                "í",
                "ị",
                "ỉ",
                "ĩ",
                "ò",
                "ó",
                "ọ",
                "ỏ",
                "õ",
                "ô",
                "ồ",
                "ố",
                "ộ",
                "ổ",
                "ỗ",
                "ơ",
                "ờ",
                "ớ",
                "ợ",
                "ở",
                "ỡ",
                "ù",
                "ú",
                "ụ",
                "ủ",
                "ũ",
                "ư",
                "ừ",
                "ứ",
                "ự",
                "ử",
                "ữ",
                "ỳ",
                "ý",
                "ỵ",
                "ỷ",
                "ỹ",
                "đ",
                "À",
                "À",
                "Ạ",
                "Ả",
                "Ã",
                "Â",
                "Ầ",
                "Ấ",
                "Ậ",
                "Ẩ",
                "Ẫ",
                "Ă",
                "Ằ",
                "Ắ",
                "Ặ",
                "Ẳ",
                "Ẵ",
                "È",
                "É",
                "Ẹ",
                "Ẻ",
                "Ẽ",
                "Ê",
                "Ề",
                "Ế",
                "Ệ",
                "Ể",
                "Ễ",
                "Ì",
                "Í",
                "Ị",
                "Ỉ",
                "Ĩ",
                "Ò",
                "Ó",
                "Ọ",
                "Ỏ",
                "Õ",
                "Ô",
                "Ồ",
                "Ố",
                "Ộ",
                "Ổ",
                "Ỗ",
                "Ơ",
                "Ờ",
                "Ớ",
                "Ợ",
                "Ở",
                "Ỡ",
                "Ù",
                "Ú",
                "Ụ",
                "Ủ",
                "Ũ",
                "Ư",
                "Ừ",
                "Ứ",
                "Ự",
                "Ử",
                "Ữ",
                "Ỳ",
                "Ý",
                "Ỵ",
                "Ỷ",
                "Ỹ",
                "Đ",
            };
            string[] precomposed =
            {
                "à",
                "á",
                "ạ",
                "ả",
                "ã",
                "â",
                "ầ",
                "ấ",
                "ậ",
                "ẩ",
                "ẫ",
                "ă",
                "ằ",
                "ắ",
                "ặ",
                "ẳ",
                "ẵ",
                "è",
                "é",
                "ẹ",
                "ẻ",
                "ẽ",
                "ê",
                "ề",
                "ế",
                "ệ",
                "ể",
                "ễ",
                "ì",
                "í",
                "ị",
                "ỉ",
                "ĩ",
                "ò",
                "ó",
                "ọ",
                "ỏ",
                "õ",
                "ô",
                "ồ",
                "ố",
                "ộ",
                "ổ",
                "ỗ",
                "ơ",
                "ờ",
                "ớ",
                "ợ",
                "ở",
                "ỡ",
                "ù",
                "ú",
                "ụ",
                "ủ",
                "ũ",
                "ư",
                "ừ",
                "ứ",
                "ự",
                "ử",
                "ữ",
                "ỳ",
                "ý",
                "ỵ",
                "ỷ",
                "ỹ",
                "đ",
                "À",
                "Á",
                "Ạ",
                "Ả",
                "Ã",
                "Â",
                "Ầ",
                "Ấ",
                "Ậ",
                "Ẩ",
                "Ẫ",
                "Ă",
                "Ằ",
                "Ắ",
                "Ặ",
                "Ẳ",
                "Ẵ",
                "È",
                "É",
                "Ẹ",
                "Ẻ",
                "Ẽ",
                "Ê",
                "Ề",
                "Ế",
                "Ệ",
                "Ể",
                "Ễ",
                "Ì",
                "Í",
                "Ị",
                "Ỉ",
                "Ĩ",
                "Ò",
                "Ó",
                "Ọ",
                "Ỏ",
                "Õ",
                "Ô",
                "Ồ",
                "Ố",
                "Ộ",
                "Ổ",
                "Ỗ",
                "Ơ",
                "Ờ",
                "Ớ",
                "Ợ",
                "Ở",
                "Ỡ",
                "Ù",
                "Ú",
                "Ụ",
                "Ủ",
                "Ũ",
                "Ư",
                "Ừ",
                "Ứ",
                "Ự",
                "Ử",
                "Ữ",
                "Ỳ",
                "Ý",
                "Ỵ",
                "Ỷ",
                "Ỹ",
                "Đ",
            };
            string[] latin =
            {
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "i",
                "i",
                "i",
                "i",
                "i",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "y",
                "y",
                "y",
                "y",
                "y",
                "d",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "a",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "e",
                "i",
                "i",
                "i",
                "i",
                "i",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "o",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "u",
                "y",
                "y",
                "y",
                "y",
                "y",
                "d",
            };

            // Convert culture specific characters
            for (int i = 0; i < decomposed.Length; i++)
            {
                slug = slug.Replace(decomposed[i], latin[i]);
                slug = slug.Replace(precomposed[i], latin[i]);
            }

            // Remove special characters
            slug = Regex.Replace(slug, @"[^a-z0-9-/ ]", "").Replace("--", "-");

            // Remove whitespaces
            slug = Regex.Replace(slug.Replace("-", " "), @"\s+", " ").Replace(" ", "-");

            // Remove slash if non-hierarchical
            if (!hierarchical)
                slug = slug.Replace("/", "-");

            // Remove multiple dashes
            slug = Regex.Replace(slug, @"[-]+", "-");

            // Remove leading & trailing dashes
            if (slug.EndsWith("-"))
                slug = slug.Substring(0, slug.LastIndexOf("-"));
            if (slug.StartsWith("-"))
                slug = slug.Substring(Math.Min(slug.IndexOf("-") + 1, slug.Length));
            return slug;
        }
    }
}
